server/config/routes.rb
Server::Application.routes.draw do

  resources :dishes

  match '/testDishes/:id', :controller=>'dishes', :action=>'mymethod'
  match 'dishes/changes/free/:id', :controller=>'dishes', :action=>'change_free_status'

  resources :tables
  match 'tables/changes/free/:id', :controller => 'tables', :action=>'change_free_status'
  match 'tables/changes/busy/:id', :controller => 'tables', :action=>'change_busy_status'
  match 'tables/changes/dirty/:id',:controller => 'tables', :action=>'change_dirty_status'
  match 'tables/filter/free', :controller=>'tables', :action=>'free'
  match 'tables/filter/busy', :controller=>'tables', :action=>'busy'
  match 'tables/filter/dirty', :controller=>'tables', :action=>'dirty'

  resources :orders
  match 'orders/filter/waiting/', :controller=>'orders', :action=>'waiting'
  match 'orders/filter/prepare/', :controller=>'orders', :action=>'prepare'
  match 'orders/changes/waiting/:id', :controller=>'orders', :action=>'change_waiting_status'
  match 'orders/changes/prepare/:id', :controller=>'orders', :action=>'change_prepare_status'

  resources :tests

  resources :temps

  resources :temp_tables

end

server/app/models/temp.rb
class Temp < ActiveRecord::Base
end

server/app/models/temp_table.rb
class TempTable < ActiveRecord::Base
end

server/app/controllers/temps_controller.rb
class TempsController < ApplicationController
  # GET /temps
  # GET /temps.json
  def index
    @temps = Temp.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @temps }
    end
  end

  # GET /temps/1
  # GET /temps/1.json
  def show
    @temp = Temp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @temp }
    end
  end

  # GET /temps/new
  # GET /temps/new.json
  def new
    @temp = Temp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @temp }
    end
  end

  # GET /temps/1/edit
  def edit
    @temp = Temp.find(params[:id])
  end

  # POST /temps
  # POST /temps.json
  def create
    @temp = Temp.new(params[:temp])

    respond_to do |format|
      if @temp.save
        format.html { redirect_to @temp, notice: 'Temp was successfully created.' }
        format.json { render json: @temp, status: :created, location: @temp }
      else
        format.html { render action: "new" }
        format.json { render json: @temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /temps/1
  # PUT /temps/1.json
  def update
    @temp = Temp.find(params[:id])

    respond_to do |format|
      if @temp.update_attributes(params[:temp])
        format.html { redirect_to @temp, notice: 'Temp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temps/1
  # DELETE /temps/1.json
  def destroy
    @temp = Temp.find(params[:id])
    @temp.destroy

    respond_to do |format|
      format.html { redirect_to temps_url }
      format.json { head :no_content }
    end
  end
end

server/app/helpers/temps_helper.rb
module TempsHelper
end

server/app/views/temps/_form.html.erb
<%= form_for(@temp) do |f| %>
  <% if @temp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temp.errors.count, "error") %> prohibited this temp from being saved:</h2>

      <ul>
      <% @temp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/temps/edit.html.erb
<h1>Editing temp</h1>

<%= render 'form' %>

<%= link_to 'Show', @temp %> |
<%= link_to 'Back', temps_path %>

server/app/views/temps/index.html.erb
<h1>Listing temps</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @temps.each do |temp| %>
  <tr>
    <td><%= temp.username %></td>
    <td><%= temp.id %></td>
    <td><%= link_to 'Show', temp %></td>
    <td><%= link_to 'Edit', edit_temp_path(temp) %></td>
    <td><%= link_to 'Destroy', temp, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Temp', new_temp_path %>

server/app/views/temps/new.html.erb
<h1>New temp</h1>

<%= render 'form' %>

<%= link_to 'Back', temps_path %>

server/app/views/temps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @temp.username %>
</p>

<p>
  <b>Id:</b>
  <%= @temp.id %>
</p>


<%= link_to 'Edit', edit_temp_path(@temp) %> |
<%= link_to 'Back', temps_path %>