server/config/routes.rb
Server::Application.routes.draw do

  resources :dishes

  match '/testDishes/:id', :controller=>'dishes', :action=>'mymethod'
  match 'dishes/changes/free/:id', :controller=>'dishes', :action=>'change_free_status'

  resources :tables
  match 'tables/changes/free/:id', :controller => 'tables', :action=>'change_free_status'
  match 'tables/changes/busy/:id', :controller => 'tables', :action=>'change_busy_status'
  match 'tables/changes/dirty/:id',:controller => 'tables', :action=>'change_dirty_status'
  match 'tables/filter/free', :controller=>'tables', :action=>'free'
  match 'tables/filter/busy', :controller=>'tables', :action=>'busy'
  match 'tables/filter/dirty', :controller=>'tables', :action=>'dirty'

  resources :orders
  match 'orders/filter/waiting/', :controller=>'orders', :action=>'waiting'
  match 'orders/filter/prepare/', :controller=>'orders', :action=>'prepare'
  match 'orders/changes/waiting/:id', :controller=>'orders', :action=>'change_waiting_status'
  match 'orders/changes/prepare/:id', :controller=>'orders', :action=>'change_prepare_status'

  resources :tests

  resources :temps

  resources :temp_tables

end

server/app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tables }
    end
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @table = Table.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table])

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render json: @table, status: :created, location: @table }
      else
        format.html { render action: 'new' }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table = Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table])
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end

  #filter all tables with status free / busy / dirty
  def free
    @tables = Table.find_all_by_status('free')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json  => @tables }
    end

    def busy
      @tables = Table.find_all_by_status('busy')
      respond_to do |format|
        format.html
        format.json { render :json => @tables }
      end
    end

    def dirty
      @tables = Table.find_all_by_status('dirty')
      respond_to do |format|
        format.html
        format.json { render :json => @tables }
      end
    end

    #modify status of table's id
    def change_free_status
      @table = Table.find(params[:id])
      if @table.status == 'free'
        @table.status = 'busy'
        @table.save
      end
      respond_to do |format|
        format.html
        format.json { render :json => @table }
      end
    end

    def change_busy_status
      @table = Table.find(params[:id])
      if @table.status == 'busy'
        @table.status = 'dirty'
        @table.save
      end
      respond_to do |format|
        format.html
        format.json { render :json => @table }
      end
    end

    def change_dirty_status
      @table = Table.find(params[:id])
      if @table.status == 'dirty'
        @table.status = 'free'
        @table.save
      end
      respond_to do |format|
        format.html
        format.json { render :json => @table }
      end
    end

  end
end

server/app/helpers/tables_helper.rb
module TablesHelper
end

server/app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :no %><br />
    <%= f.number_field :no %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

server/app/views/tables/index.html.erb
<h1>Listing tables</h1>

<table>
  <tr>
    <th>Id</th>
    <th>No</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tables.each do |table| %>
  <tr>
    <td><%= table.id %></td>
    <td><%= table.no %></td>
    <td><%= table.status %></td>
    <td><%= link_to 'Show', table %></td>
    <td><%= link_to 'Edit', edit_table_path(table) %></td>
    <td><%= link_to 'Destroy', table, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Table', new_table_path %>

server/app/views/tables/new.html.erb
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

server/app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @table.id %>
</p>

<p>
  <b>No:</b>
  <%= @table.no %>
</p>

<p>
  <b>Status:</b>
  <%= @table.status %>
</p>


<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>