server/config/routes.rb
Server::Application.routes.draw do

  resources :dishes

  match '/testDishes/:id', :controller=>'dishes', :action=>'mymethod'
  match 'dishes/changes/free/:id', :controller=>'dishes', :action=>'change_free_status'

  resources :tables
  match 'tables/changes/free/:id', :controller => 'tables', :action=>'change_free_status'
  match 'tables/changes/busy/:id', :controller => 'tables', :action=>'change_busy_status'
  match 'tables/changes/dirty/:id',:controller => 'tables', :action=>'change_dirty_status'
  match 'tables/filter/free', :controller=>'tables', :action=>'free'
  match 'tables/filter/busy', :controller=>'tables', :action=>'busy'
  match 'tables/filter/dirty', :controller=>'tables', :action=>'dirty'

  resources :orders
  match 'orders/filter/waiting/', :controller=>'orders', :action=>'waiting'
  match 'orders/filter/prepare/', :controller=>'orders', :action=>'prepare'
  match 'orders/changes/waiting/:id', :controller=>'orders', :action=>'change_waiting_status'
  match 'orders/changes/prepare/:id', :controller=>'orders', :action=>'change_prepare_status'

  resources :tests

  resources :temps

  resources :temp_tables

end

server/app/models/dish.rb
class Dish < ActiveRecord::Base
end

server/app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dishes }
    end
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
    @dish = Dish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/new
  # GET /dishes/new.json
  def new
    @dish = Dish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/1/edit
  def edit
    @dish = Dish.find(params[:id])
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(params[:dish])

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render json: @dish, status: :created, location: @dish }
      else
        format.html { render action: "new" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dishes/1
  # PUT /dishes/1.json
  def update
    @dish = Dish.find(params[:id])

    respond_to do |format|
      if @dish.update_attributes(params[:dish])
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to dishes_url }
      format.json { head :no_content }
    end
  end

  def change_free_status

  end
end

server/app/helpers/dishes_helper.rb
module DishesHelper
end

server/app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :DishID %><br />
    <%= f.number_field :DishID %>
  </div>
  <div class="field">
    <%= f.label :DishName %><br />
    <%= f.text_field :DishName %>
  </div>
  <div class="field">
    <%= f.label :Price %><br />
    <%= f.text_field :Price %>
  </div>
  <div class="field">
    <%= f.label :Discount %><br />
    <%= f.text_field :Discount %>
  </div>
  <div class="field">
    <%= f.label :Currency %><br />
    <%= f.text_field :Currency %>
  </div>
  <div class="field">
    <%= f.label :Tag %><br />
    <%= f.text_field :Tag %>
  </div>
  <div class="field">
    <%= f.label :BuyNum %><br />
    <%= f.text_field :BuyNum %>
  </div>
  <div class="field">
    <%= f.label :DishImage %><br />
    <%= f.text_field :DishImage %>
  </div>
  <div class="field">
    <%= f.label :Description %><br />
    <%= f.text_area :Description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

server/app/views/dishes/index.html.erb
<h1>Listing dishes</h1>

<table>
  <tr>
    <th>Dishid</th>
    <th>Dishname</th>
    <th>Price</th>
    <th>Discount</th>
    <th>Currency</th>
    <th>Tag</th>
    <th>Buynum</th>
    <th>Dishimage</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dishes.each do |dish| %>
  <tr>
    <td><%= dish.DishID %></td>
    <td><%= dish.DishName %></td>
    <td><%= dish.Price %></td>
    <td><%= dish.Discount %></td>
    <td><%= dish.Currency %></td>
    <td><%= dish.Tag %></td>
    <td><%= dish.BuyNum %></td>
    <td><%= dish.DishImage %></td>
    <td><%= dish.Description %></td>
    <td><%= link_to 'Show', dish %></td>
    <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
    <td><%= link_to 'Destroy', dish, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dish', new_dish_path %>

server/app/views/dishes/mymethod.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dishid:</b>
  <%= @dish.DishID %>
</p>

<p>
  <b>Dishname:</b>
  <%= @dish.DishName %>
</p>

<p>
  <b>Price:</b>
  <%= @dish.Price %>
</p>

<p>
  <b>Discount:</b>
  <%= @dish.Discount %>
</p>

<p>
  <b>Currency:</b>
  <%= @dish.Currency %>
</p>

<p>
  <b>Tag:</b>
  <%= @dish.Tag %>
</p>

<p>
  <b>Dishimage:</b>
  <%= @dish.DishImage %>
</p>

<p>
  <b>Description:</b>
  <%= @dish.Description %>
</p>


<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

server/app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

server/app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dishid:</b>
  <%= @dish.DishID %>
</p>

<p>
  <b>Dishname:</b>
  <%= @dish.DishName %>
</p>

<p>
  <b>Price:</b>
  <%= @dish.Price %>
</p>

<p>
  <b>Discount:</b>
  <%= @dish.Discount %>
</p>

<p>
  <b>Currency:</b>
  <%= @dish.Currency %>
</p>

<p>
  <b>Tag:</b>
  <%= @dish.Tag %>
</p>

<p>
  <b>Buynum:</b>
  <%= @dish.BuyNum %>
</p>

<p>
  <b>Dishimage:</b>
  <%= @dish.DishImage %>
</p>

<p>
  <b>Description:</b>
  <%= @dish.Description %>
</p>


<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>