server/config/routes.rb
Server::Application.routes.draw do

  resources :dishes

  match '/testDishes/:id', :controller=>'dishes', :action=>'mymethod'
  match 'dishes/changes/free/:id', :controller=>'dishes', :action=>'change_free_status'

  resources :tables
  match 'tables/changes/free/:id', :controller => 'tables', :action=>'change_free_status'
  match 'tables/changes/busy/:id', :controller => 'tables', :action=>'change_busy_status'
  match 'tables/changes/dirty/:id',:controller => 'tables', :action=>'change_dirty_status'
  match 'tables/filter/free', :controller=>'tables', :action=>'free'
  match 'tables/filter/busy', :controller=>'tables', :action=>'busy'
  match 'tables/filter/dirty', :controller=>'tables', :action=>'dirty'

  resources :orders
  match 'orders/filter/waiting/', :controller=>'orders', :action=>'waiting'
  match 'orders/filter/prepare/', :controller=>'orders', :action=>'prepare'
  match 'orders/changes/waiting/:id', :controller=>'orders', :action=>'change_waiting_status'
  match 'orders/changes/prepare/:id', :controller=>'orders', :action=>'change_prepare_status'

  resources :tests

  resources :temps

  resources :temp_tables

end

server/app/controllers/temp_tables_controller.rb
class TempTablesController < ApplicationController
  # GET /temp_tables
  # GET /temp_tables.json
  def index
    @temp_tables = TempTable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @temp_tables }
    end
  end

  # GET /temp_tables/1
  # GET /temp_tables/1.json
  def show
    @temp_table = TempTable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @temp_table }
    end
  end

  # GET /temp_tables/new
  # GET /temp_tables/new.json
  def new
    @temp_table = TempTable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @temp_table }
    end
  end

  # GET /temp_tables/1/edit
  def edit
    @temp_table = TempTable.find(params[:id])
  end

  # POST /temp_tables
  # POST /temp_tables.json
  def create
    @temp_table = TempTable.new(params[:temp_table])

    respond_to do |format|
      if @temp_table.save
        format.html { redirect_to @temp_table, notice: 'Temp table was successfully created.' }
        format.json { render json: @temp_table, status: :created, location: @temp_table }
      else
        format.html { render action: "new" }
        format.json { render json: @temp_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /temp_tables/1
  # PUT /temp_tables/1.json
  def update
    @temp_table = TempTable.find(params[:id])

    respond_to do |format|
      if @temp_table.update_attributes(params[:temp_table])
        format.html { redirect_to @temp_table, notice: 'Temp table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @temp_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temp_tables/1
  # DELETE /temp_tables/1.json
  def destroy
    @temp_table = TempTable.find(params[:id])
    @temp_table.destroy

    respond_to do |format|
      format.html { redirect_to temp_tables_url }
      format.json { head :no_content }
    end
  end
end

server/app/helpers/temp_tables_helper.rb
module TempTablesHelper
end

server/app/views/temp_tables/_form.html.erb
<%= form_for(@temp_table) do |f| %>
  <% if @temp_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temp_table.errors.count, "error") %> prohibited this temp_table from being saved:</h2>

      <ul>
      <% @temp_table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/temp_tables/edit.html.erb
<h1>Editing temp_table</h1>

<%= render 'form' %>

<%= link_to 'Show', @temp_table %> |
<%= link_to 'Back', temp_tables_path %>

server/app/views/temp_tables/index.html.erb
<h1>Listing temp_tables</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @temp_tables.each do |temp_table| %>
  <tr>
    <td><%= temp_table.name %></td>
    <td><%= temp_table.id %></td>
    <td><%= link_to 'Show', temp_table %></td>
    <td><%= link_to 'Edit', edit_temp_table_path(temp_table) %></td>
    <td><%= link_to 'Destroy', temp_table, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Temp table', new_temp_table_path %>

server/app/views/temp_tables/new.html.erb
<h1>New temp_table</h1>

<%= render 'form' %>

<%= link_to 'Back', temp_tables_path %>

server/app/views/temp_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @temp_table.name %>
</p>

<p>
  <b>Id:</b>
  <%= @temp_table.id %>
</p>


<%= link_to 'Edit', edit_temp_table_path(@temp_table) %> |
<%= link_to 'Back', temp_tables_path %>